---
repos:
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.2.0
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@15.11.0
          - stylelint-config-standard@34.0.0
          - stylelint-plugin-stylus@^1.0.0
          - stylelint-config-html@1.1.0
          - postcss-html@1.0.0
          - postcss-markdown@1.0.0
